### ISSUE TITLE
Crash when trying to move to previous image if no image is loaded

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/Coreavor#4]
### Steps to reproduce -

- Start coreavor
- Hit `Previous` button

### Proposed solution -
Grey out the previous and next button if no image is loaded.
Also disable any shortcuts like arrow keys that can trigger this action.

**Comment by Gabriel-nps** [comment]
I would like to contribute to this issue.

**Comment by Mithil467** [comment]
Hey @GabrielFalcom 👋🏼 
That would be awesome! Please refer to the [contributing](https://github.com/Mithil467/Coreavor/blob/master/CONTRIBUTING.md) guidelines before starting. 😄
